package uz.online.model;

public enum BotState {

    CRUD_MENU,

    SUBJECT_MENU,   TEST_MENU,   ANSWER_MENU,
    SUBJECT_CREATE, TEST_CREATE, ANSWER_CREATE,
    SUBJECT_UPDATE, TEST_UPDATE, ANSWER_UPDATE,
    SUBJECT_DELETE, TEST_DELETE, ANSWER_DELETE,
    SUBJECT_LIST,   TEST_LIST,   ANSWER_LIST,
    DEFAULT

}
